# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='url',
            field=models.URLField(blank=True, max_length=300, verbose_name='URL'),
        ),
    ]
