# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='shop_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Shop code'),
        ),
        migrations.AddField(
            model_name='article',
            name='shop_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Shop price'),
        ),
        migrations.AddField(
            model_name='article',
            name='shop_url',
            field=models.URLField(blank=True, verbose_name='Shop URL'),
        ),
    ]
