# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_detailed_info', models.BooleanField(default=False, verbose_name='Parse detailed info?')),
                ('initial_request_url', models.URLField(blank=True, verbose_name='Initial request URL')),
                ('next_page_xpath', models.TextField(blank=True, verbose_name='Next page XPath')),
                ('selector_xpath', models.TextField(blank=True, verbose_name='Selector XPath')),
                ('code_type', models.IntegerField(choices=[(0, 'list'), (1, 'detail'), (2, 'custom')], default=0)),
                ('code', models.TextField(blank=True, verbose_name='code')),
                ('code_in', models.TextField(blank=True, verbose_name='code input')),
                ('code_out', models.TextField(blank=True, verbose_name='code output')),
                ('shop_title_type', models.IntegerField(choices=[(0, 'list'), (1, 'detail'), (2, 'custom')], default=0)),
                ('shop_title', models.TextField(blank=True, verbose_name='shop_title')),
                ('shop_title_in', models.TextField(blank=True, verbose_name='shop_title input')),
                ('shop_title_out', models.TextField(blank=True, verbose_name='shop_title output')),
                ('url_type', models.IntegerField(choices=[(0, 'list'), (1, 'detail'), (2, 'custom')], default=0)),
                ('url', models.TextField(blank=True, verbose_name='url')),
                ('url_in', models.TextField(blank=True, verbose_name='url input')),
                ('url_out', models.TextField(blank=True, verbose_name='url output')),
                ('price_type', models.IntegerField(choices=[(0, 'list'), (1, 'detail'), (2, 'custom')], default=0)),
                ('price', models.TextField(blank=True, verbose_name='price')),
                ('price_in', models.TextField(blank=True, verbose_name='price input')),
                ('price_out', models.TextField(blank=True, verbose_name='price output')),
                ('shop_availability_type', models.IntegerField(choices=[(0, 'list'), (1, 'detail'), (2, 'custom')], default=0)),
                ('shop_availability', models.TextField(blank=True, verbose_name='shop_availability')),
                ('shop_availability_in', models.TextField(blank=True, verbose_name='shop_availability input')),
                ('shop_availability_out', models.TextField(blank=True, verbose_name='shop_availability output')),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
            options={
                'db_table': 'spiders',
                'verbose_name': 'Spider',
                'verbose_name_plural': 'Spiders',
            },
        ),
    ]
