# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spider',
            old_name='code',
            new_name='shop_code',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='code_in',
            new_name='shop_code_in',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='code_out',
            new_name='shop_code_out',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='code_type',
            new_name='shop_code_type',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='price',
            new_name='shop_price',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='price_in',
            new_name='shop_price_in',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='price_out',
            new_name='shop_price_out',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='price_type',
            new_name='shop_price_type',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='url',
            new_name='shop_url',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='url_in',
            new_name='shop_url_in',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='url_out',
            new_name='shop_url_out',
        ),
        migrations.RenameField(
            model_name='spider',
            old_name='url_type',
            new_name='shop_url_type',
        ),
    ]
