# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20161009_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='next_page_is_ajax_req',
            field=models.BooleanField(default=False, verbose_name='Is next page AJAX request?'),
        ),
    ]
