# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_spider_next_page_is_ajax_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='next_page_is_ajax_req',
        ),
        migrations.AddField(
            model_name='spider',
            name='next_page_is_calc',
            field=models.BooleanField(default=False, verbose_name='Is next page calculated manually?'),
        ),
    ]
